version: "2017-09-20"
pipeline:
- id: build
  type: script
  when:
    event: push
    branch: master
  commands:
  - desc: Install Docker
    cmd: |
      # Docker
      curl -fLOsS https://delivery.cloud.zalando.com/utils/ensure-docker && sh ensure-docker && rm ensure-docker
  - desc: Build docker image
    cmd: |
      GIT_TAG=$(git describe --tags --always --dirty)
      IMAGE=registry-write.opensource.zalan.do/tip/docker-locust:$GIT_TAG
      echo "Image: $IMAGE"
      echo "Build docker image"
      docker build -t $IMAGE --build-arg DL_IMAGE_VERSION=$GIT_TAG .
  - desc: Run smoke test
    cmd: |
        echo "Deploy image locally and run simple scenario"
        ./local.sh deploy --target=https://google.com --locust-file=./example/simple.py --slaves=2 --mode=auto --users=2 --hatch-rate=1 --duration=5
        # check if report html file exists
        ls -l reports | grep reports.html || exit 1
        # check if file size is larger than 0
        [ -s reports/reports.html ] || exit 1
        # check if RPS value is greater than 0
        cat reports/reports.html | grep 'RPS:' | cut -c 17- | awk -F'</strong' {'print $1">0"'} | bc -l | grep 1 || exit 1
  - desc: Push docker image
    cmd: |
        echo "Push docker image"
        docker push $IMAGE
