version: "2017-09-20"
notifications:
  hipchat:
    rooms:
      - "DP - TIP"
pipeline:
- id: build
  type: script
  when:
    event: push
    branch: master
  commands:
  - desc: Install Docker
    cmd: |
      # Docker
      curl -fLOsS https://delivery.cloud.zalando.com/utils/ensure-docker && sh ensure-docker && rm ensure-docker
  - desc: Build docker image
    cmd: |
      export GIT_TAG=$(git describe --tags --always --dirty)
      export IMAGE=registry-write.opensource.zalan.do/tip/docker-locust:$GIT_TAG
      echo "Image: $IMAGE"
      echo "Build docker image"
      docker build -t $IMAGE --build-arg DL_IMAGE_VERSION=$GIT_TAG .
  - desc: Run smoke test
    cmd: |
      echo "Deploy image locally and run simple scenario"
      ./local.sh deploy --target=https://google.com --locust-file=./example/simple.py --slaves=2 --mode=auto --users=2 --hatch-rate=1 --duration=5
      # check if json report exists and has non-zero size
      [ -s reports/requests.json ] || exit 1
      # check if html report exists and has non-zero size
      [ -s reports/reports.html ] || exit 1
      # check if RPS value is greater than 0
      cat reports/reports.html | grep 'RPS:' | cut -c 17- | awk -F'</strong' '{print ($1>0)}' | grep 1 || exit 1
      # 
  - desc: Push docker image
    cmd: |
      echo "Push docker image"
      docker push $IMAGE
